11/08/24 01:54:21 PM Sunday - [ WARNING]  Error '[WinError 10061] No connection could be made because the target machine actively refused it' while sending data via fluent for tag 'test': '{'status': 'start', 'stage': 'session', 'sessionId': '63f4c173-a179-4e15-a934-dd32c9400159'}' (event.py:53)
11/08/24 01:54:23 PM Sunday - [ WARNING]  Error '[WinError 10061] No connection could be made because the target machine actively refused it' while sending data via fluent for tag 'test': '{'status': 'start', 'stage': 'testcase', 'sessionId': '63f4c173-a179-4e15-a934-dd32c9400159', 'testId': 'e7683a88-dd52-41d2-846b-3ec7fe11bcdf', 'name': 'APIPetstoretest/test_basics.py::test_getPetById_response'}' (event.py:53)
11/08/24 01:54:28 PM Sunday - [ WARNING]  Error '[WinError 10061] No connection could be made because the target machine actively refused it' while sending data via fluent for tag 'test': '{'name': 'APIPetstoretest/test_basics.py::test_getPetById_response', 'outcome': 'error', 'duration': 2.600168199998734, 'markers': {'test_getPetById_response': 1, 'test_basics.py': 1, 'APIPetstoretest': 1, 'APITESTINGFRAMEWORK': 1, '': 1}, 'failure_message': "def test_getPetById_response():\n    \n        url = baseURI + petID\n        data, status, timeTaken = getAPIData(url)\n        # assert_that(data['name']).is_equal_to('mitch')\n>       assert_that(status).is_equal_to(200)\nE       AssertionError: Expected <404> to be equal to <200>, but was not.\n\ntest_basics.py:18: AssertionError", 'stage': 'testcase', 'when': 'call', 'sessionId': '63f4c173-a179-4e15-a934-dd32c9400159', 'testId': 'e7683a88-dd52-41d2-846b-3ec7fe11bcdf'}' (event.py:53)
11/08/24 01:54:30 PM Sunday - [ WARNING]  Error '[WinError 10061] No connection could be made because the target machine actively refused it' while sending data via fluent for tag 'test': '{'status': 'finish', 'stage': 'testcase', 'sessionId': '63f4c173-a179-4e15-a934-dd32c9400159', 'testId': 'e7683a88-dd52-41d2-846b-3ec7fe11bcdf', 'name': 'APIPetstoretest/test_basics.py::test_getPetById_response'}' (event.py:53)
11/08/24 01:54:32 PM Sunday - [ WARNING]  Error '[WinError 10061] No connection could be made because the target machine actively refused it' while sending data via fluent for tag 'test': '{'status': 'finish', 'duration': 11.302971839904785, 'stage': 'session', 'sessionId': '63f4c173-a179-4e15-a934-dd32c9400159'}' (event.py:53)
